package com.healthcare.triage.common;

import java.util.EnumSet;
import java.util.Map;
import java.util.Set;

public enum TriageState {
    INTAKE_IN_PROGRESS,
    INTAKE_COMPLETED,
    SAFETY_EVALUATED,
    EMERGENCY_DECLARED,
    AI_ASSESSED,
    ROUTINE_TRIAGED,
    URGENT_TRIAGED,
    CONFLICT_DETECTED,
    INSUFFICIENT_INFO_FLAGGED,
    AWAITING_CLINICIAN_REVIEW,
    CLINICIAN_ACCEPTED,
    CLINICIAN_OVERRIDDEN,
    EMERGENCY_DISPATCHED,
    RESOLVED,
    FAILED;

    private static final Map<TriageState, Set<TriageState>> VALID_TRANSITIONS = Map.ofEntries(
            Map.entry(INTAKE_IN_PROGRESS, EnumSet.of(INTAKE_COMPLETED, FAILED)),
            Map.entry(INTAKE_COMPLETED, EnumSet.of(SAFETY_EVALUATED, FAILED)),
            Map.entry(SAFETY_EVALUATED, EnumSet.of(EMERGENCY_DECLARED, AI_ASSESSED, CONFLICT_DETECTED, FAILED)),
            Map.entry(EMERGENCY_DECLARED, EnumSet.of(AWAITING_CLINICIAN_REVIEW, CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, EMERGENCY_DISPATCHED, RESOLVED, FAILED)),
            Map.entry(AI_ASSESSED, EnumSet.of(ROUTINE_TRIAGED, URGENT_TRIAGED, CONFLICT_DETECTED, INSUFFICIENT_INFO_FLAGGED, AWAITING_CLINICIAN_REVIEW, CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, FAILED)),
            Map.entry(ROUTINE_TRIAGED, EnumSet.of(AWAITING_CLINICIAN_REVIEW, CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, RESOLVED, FAILED)),
            Map.entry(URGENT_TRIAGED, EnumSet.of(AWAITING_CLINICIAN_REVIEW, CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, RESOLVED, FAILED)),
            Map.entry(CONFLICT_DETECTED, EnumSet.of(AWAITING_CLINICIAN_REVIEW, CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, EMERGENCY_DISPATCHED, RESOLVED, FAILED)),
            Map.entry(INSUFFICIENT_INFO_FLAGGED, EnumSet.of(INTAKE_IN_PROGRESS, AWAITING_CLINICIAN_REVIEW, CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, RESOLVED, FAILED)),
            Map.entry(AWAITING_CLINICIAN_REVIEW, EnumSet.of(CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, EMERGENCY_DISPATCHED, RESOLVED, FAILED)),
            Map.entry(CLINICIAN_ACCEPTED, EnumSet.of(CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, EMERGENCY_DISPATCHED, RESOLVED, FAILED)),
            Map.entry(CLINICIAN_OVERRIDDEN, EnumSet.of(CLINICIAN_ACCEPTED, CLINICIAN_OVERRIDDEN, EMERGENCY_DISPATCHED, RESOLVED, FAILED)),
            Map.entry(EMERGENCY_DISPATCHED, EnumSet.of(RESOLVED, FAILED)),
            Map.entry(RESOLVED, EnumSet.noneOf(TriageState.class)),
            Map.entry(FAILED, EnumSet.of(AWAITING_CLINICIAN_REVIEW, RESOLVED))
    );

    public boolean canTransitionTo(TriageState nextState) {
        if (this == nextState) return true; // Idempotent same-state
        Set<TriageState> allowed = VALID_TRANSITIONS.getOrDefault(this, EnumSet.noneOf(TriageState.class));
        return allowed.contains(nextState);
    }
}
